### PR TITLE
removed 'event_duration' from calculation, fixes #24

### LINKED ISSUE #24: age_in_seconds is wrong
Calculation is mistakenly adding `event_duration`; should be difference between when the cert was created and when the claim was made (i.e., `now()`).

### PR DESCRIPTION
**Pull request by cgrayson**
@alexkwolfe take a look, and also let me know if you want this deployed now, or held until Thursday.

### CODE REVIEW

File: spec/claim_spec.coffee [hunk 1]
```diff
@@ -283,12 +283,13 @@ describe 'Claim Response', ->
...
+      it 'calculates age in seconds', ->
         vars = {}
-        body = event_duration: 61999
+        body = {}
         response = getResponse(body, vars)
-        assert.equal response.age_in_seconds, 172353 # 172291s + 61.999s
-
+        # cert.created_at:  "2014-04-02T21:24:22Z"
+        # timekeeper "now": "2014-04-04T21:15:52.539Z"
+        assert.equal response.age_in_seconds, 172291 # ~ 47.86 h
```
Comment (alexkwolfe) [inline spec/claim_spec.coffee]: This test was meant to ensure that the age does not include the time on page. I'm looking at this on my phone so it's hard to be sure, but it appears that this test no longer does that.

File: src/claim.coffee [hunk 2]
```diff
@@ -65,7 +65,6 @@ validate = (vars) ->
 
 ageInSeconds = (cert) ->
   difference = Date.now() - new Date(cert.created_at)
-  difference += parseInt(cert.event_duration) if cert.event_duration? and not isNaN(cert.event_duration)
```
Comment (alexkwolfe) [inline src/claim.coffee]: I think you want to keep this line, no? The operator should just be changed to `-=`, isn't that right?

File: spec/claim_spec.coffee (hunk 1 above)
Comment (cgrayson) [inline spec/claim_spec.coffee]: Oh. I misunderstood (again) what "age in seconds" means. You said in Slack it's the time since last event, which TF doesn't provide. It provides created-at, so I thought you misspoke. But you meant that you want the integration to _calculate_ the time of the last event, by adding event-duration to created-at.

**Comment by cgrayson** [comment]
Back to you, @alexkwolfe

File: src/claim.coffee [hunk 3]
```diff
@@ -64,9 +64,9 @@ validate = (vars) ->
 #
 
 ageInSeconds = (cert) ->
-  difference = Date.now() - new Date(cert.created_at)
-  difference += parseInt(cert.event_duration) if cert.event_duration? and not isNaN(cert.event_duration)
-  Math.round difference / 1000
+  timeOnPage = timeOnPageInSeconds(cert.event_duration) or 0
+  certAge = (Date.now() - new Date(cert.created_at)) / 1000
```
Comment (alexkwolfe) [inline src/claim.coffee]: Is it worth it to use `claim.created_at` here rather than `Date.now()`?

**Comment by alexkwolfe** [comment]
Other than that one comment, LGTM.

**Comment by cgrayson** [comment]
Wound up adding more code than expected, because `claims` is an array. Give another look anyway, @alexkwolfe, despite the previous LG?

File: src/claim.coffee [hunk 4]
```diff
@@ -64,10 +64,16 @@ validate = (vars) ->
...
-  difference = Date.now() - new Date(cert.created_at)
-  difference += parseInt(cert.event_duration) if cert.event_duration? and not isNaN(cert.event_duration)
-  Math.round difference / 1000
+  timeOnPage = timeOnPageInSeconds(cert.event_duration) or 0
 
+  latestClaim = cert.claims.sort( (a, b) ->
+    return -1 if a.created_at < b.created_at
+    return 1 if a.created_at > b.created_at
+    return 0
+  )[cert.claims.length - 1]
```
Comment (alexkwolfe) [inline src/claim.coffee]: This routine to find the latest claim isn't necessary. The claim API returns the claim being made. If the `event` were passed to this function instead of the cert, then you'd could call `event.created_at` to get the claim's creation date.
